import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< Updated upstream
=======
import { FeedbackProvider } from "../../context/FeedbackProvider";
import NavigationLoader from "@shared/components/NavigationLoader";
>>>>>>> Stashed changes

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< Updated upstream
        {children}
=======
        <NavigationLoader />
        <FeedbackProvider>
          {children}
        </FeedbackProvider>
>>>>>>> Stashed changes
      </body>
    </html>
  );
}
